// <auto-generated />
using API.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(Datacontext))]
    partial class DatacontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PercentCoal")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentGeothermalBiomass")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentHydro")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentNaturalGas")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentNuclear")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentOil")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentSolar")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentWind")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
